# **Assignment: Working with Files and JSON in Python**
---
**Name            :** Parameswari Manthiramoorthi  
**ID No           :** IITP_AIMLTN_2602771  
**Course          :** Applied AI and ML Essential  
**Submission Date :** 23-02-2026

---


**Objective:**

To manage a bookstore inventory stored in a JSON file — read the file, update it with new books, and display the inventory neatly.

Task :
* You are helping a small bookstore save and manage their inventory.
* The store currently has a list of books stored in a file called ***inventory.json.***
* Your job is to read the inventory, make changes, and save it back — all using proper Python file-handling practices.
* You are given the following starter file ***inventory.json***:

```
[
  {"title": "The Alchemist", "author": "Paulo Coelho", "price": 12.99, "in_stock": true},
  {"title": "1984", "author": "George Orwell", "price": 9.99, "in_stock": true}
]
```


And the following new book to add:

```
new_book = {"title": "Atomic Habits", "author": "James Clear", "price": 14.99, "in_stock": True}

```




In [46]:
# save  list of books stored in a file called inventory.json.
import json   # import json module to work with json file

# create invenory list , list contains title ,author, price and stock availability
inventory = [
  {"title": "The Alchemist", "author": "Paulo Coelho", "price": 12.99, "in_stock": True},
  {"title": "1984", "author": "George Orwell", "price": 9.99, "in_stock": True}
]

# for safty purpose "with" blocks is recommended,
# create inventery.json file with ("w") write mode
with open("inventory.json", "w") as f:
  # json.dump() to save python list to json string
  json.dump(inventory, f, indent=4)

# For confirmation  printed message
print("inventory.json created!")

inventory.json created!


**Task 1 — Read the inventory**
Open ***inventory.json*** using a with block and load its contents into a variable called ***inventory***. Print the total number of books currently in the file.



In [47]:
# open inventory.json file in ('r') read mode
with open("inventory.json", "r") as f:
  # json.load convert json string to python variable
  loaded_inventory = json.load(f)

print("-" * 25)
# print total number of books in the list
print("Total No of books:", len(loaded_inventory))
print("-" * 25)

-------------------------
Total No of books: 2
-------------------------


**Task 2 — Update and save Append** new_book to the inventory list. Write the updated list back to ***inventory.json*** using a **with** block, with an **indentation** of **4** spaces.


In [44]:
# load file
loaded_inventory

[{'title': 'The Alchemist',
  'author': 'Paulo Coelho',
  'price': 12.99,
  'in_stock': True},
 {'title': '1984', 'author': 'George Orwell', 'price': 9.99, 'in_stock': True}]

In [25]:
type(loaded_inventory)

list

In [48]:
# Update and save Append new_book to the inventory list
new_book = {"title": "Atomic Habits", "author": "James Clear", "price": 14.99, "in_stock": True}
# append used to add new book into loaded_inventory
loaded_inventory.append(new_book)
loaded_inventory


[{'title': 'The Alchemist',
  'author': 'Paulo Coelho',
  'price': 12.99,
  'in_stock': True},
 {'title': '1984', 'author': 'George Orwell', 'price': 9.99, 'in_stock': True},
 {'title': 'Atomic Habits',
  'author': 'James Clear',
  'price': 14.99,
  'in_stock': True}]

In [49]:
# Write the updated list back to inventory.json using a with block, with an indentation of 4 spaces.
with open("inventory.json" ,'w') as f:
  # json.dump() to save the updated list
  json.dump(loaded_inventory , f ,indent=4)
# for confirmation Printed a  message.
print(" updated list in inventory.json successfully ")

 updated list in inventory.json successfully 


**Task 3 — Display the inventory**
* Read the updated file again

In [29]:
# read the updated file again
with open("inventory.json",'r') as f:
  details = json.load(f)
print(details)

[{'title': 'The Alchemist',
  'author': 'Paulo Coelho',
  'price': 12.99,
  'in_stock': True},
 {'title': '1984', 'author': 'George Orwell', 'price': 9.99, 'in_stock': True},
 {'title': 'Atomic Habits',
  'author': 'James Clear',
  'price': 14.99,
  'in_stock': True}]

**Print each book's details in the following format:**
```
Title: The Alchemist   | Author: Paulo Coelho  | Price: $12.99
Title: 1984            | Author: George Orwell | Price: $9.99
Title: Atomic Habits   | Author: James Clear   | Price: $14.99
```

In [40]:
print("-"*65)
print("-------------------------Book's Details--------------------------")
print("-"*65)
for book in details:
  print(f" Title : {book['title']:<10} \t | Author : {book['author']:<10} \t | Price : ${book['price']:<10}")
print("-"*65)

-----------------------------------------------------------------
-------------------------Book's Details--------------------------
-----------------------------------------------------------------
 Title : The Alchemist 	 | Author : Paulo Coelho 	 | Price : $12.99     
 Title : 1984       	 | Author : George Orwell 	 | Price : $9.99      
 Title : Atomic Habits 	 | Author : James Clear 	 | Price : $14.99     
-----------------------------------------------------------------


#**Summary**

- **JSON** is used to **store and manage structured data**, such as a list of books in the inventory.  
- **`with open()`** blocks handle **file operations safely**, ensuring the file is automatically closed after reading or writing.  
- **`json.load()`** converts JSON data into **Python objects**, while **`json.dump()`** writes Python objects back to a JSON file with proper formatting.  
- **Lists** allow you to **append new items**, making the inventory **dynamic and easy to update**.  
- **F-strings with alignment** are used to display **book details clearly and neatly**, forming a **readable table-like output**.  
- Using **indentation** in **`json.dump()`** improves **file readability**, making it easier to view and edit the inventory manually if needed.  
- Overall, the program demonstrates **safe file handling**, **dynamic data management**, and **clean output formatting** in **Python**.

- **Conclusion:** The program shows how to safely handle files, manage dynamic data, and display information neatly in Python.

___


